<?php

declare(strict_types=1);

namespace App\Storage\Domain;

/**
 * Where the bytes actually live (§15, non-negotiable #9).
 *
 * A port for the same reason the payment provider is one: the domain must not
 * learn whether this is a filesystem, S3, or something else. Nothing above
 * this interface knows what a `$key` addresses — it is opaque, generated by
 * this platform, and never derived from anything a client sent.
 *
 * Deliberately narrow. There is no `list()`, because the database is the
 * catalogue and a second one that could disagree with it is worse than none.
 */
interface StorageProvider
{
    /**
     * Writes an object, replacing anything already at that key.
     *
     * @throws StorageFailure when the object cannot be written
     */
    public function put(string $key, string $contents): void;

    /**
     * @throws StorageFailure when the object is missing or unreadable
     */
    public function get(string $key): string;

    /**
     * Removes an object. Succeeds if it was already gone: the caller wants it
     * absent, and it is.
     */
    public function delete(string $key): void;

    public function exists(string $key): bool;
}
